### ISSUE TITLE
Different version shown on the module list and the front and module pages

### ISSUE THREAD

**Issue by vojtechtrefny** [cfengine/build-website#33]
For example for the /etc/hosts module, version *0.1.1* is shown on the from page (and on the [module page ](https://build.cfengine.com/modules) too):

![image](https://user-images.githubusercontent.com/5063197/139825390-87f972b4-2840-49a7-8bb5-0d7087ce072d.png)
![image](https://user-images.githubusercontent.com/5063197/139825999-d37daa64-2a04-4925-979b-e64b479fd0a4.png)

but the module detail shows *1.1.0* in the dropdown box (AFAICT the same version is shown for all modules in the dropdown):

![image](https://user-images.githubusercontent.com/5063197/139825245-574ba0c0-c93d-43d4-9291-a4f66fc14077.png)

I'm not sure which version is the correct one here, but from [the module repository](https://github.com/nickanderson/cfengine-inventory-etc-hosts/blob/a825e655af3bdfc6939186882e3b1b3292a8aa70/cfbs.json), it looks like it should be *1.0.0*.

**Comment by olehermanse** [comment]
@vojtechtrefny Thank you for reporting this! We are working on it already - the version dropdown on the website will be fixed soon.

The correct versions can be seen here: https://github.com/cfengine/build-index/blob/master/cfbs.json

In this case it is 0.1.1.

The JSON you are linking to in the inventory-etc-hosts has been changed (in the main branch of that repo):

https://github.com/nickanderson/cfengine-inventory-etc-hosts/blob/main/cfbs.json

We will update this module with a new README and a new version in the index, to reduce the confusion here.
